### ISSUE TITLE
Input data seems to be way more than just nine images

### ISSUE THREAD

**Issue by jclarkk** [zju3dv/AutoRecon#3]
Hi

First of all, thank you for sharing this fantastic project!

It seems on the project page and in the paper that the input can be as little as 9 images in the wild, but it uses around 200 images in a sequential capture when running the project on custom data. Since I've played with hloc in the past, I know that it can't use a low amount of sparse imagery so I wonder how you were able to do a 3D asset from just 9 images in the project page.

**Comment by angshine** [comment]
Hi there, I apologize for any confusion caused by the illustration. We did not claim that we can reconstruct a 3D asset from just 9 images. However, we also don’t need 200 images. The demo data is just a sequence from CO3D. We took 40 frames in the demo script and you can try running the pipeline with less images (like 20) as well.

**Comment by jclarkk** [comment]
Gotcha, thanks a lot for the clarification!
